# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 817b9126de4e3a53ccda08f9b720d0b144e07b775255b306f2614d805a1507594521c3a94b2f9a01ae39b1e77404b5d1c8210256cbb706780db27f0391793537

test:
  secret_key_base: c542ab6de951bf210a483d5ccc16577dd3bcea4a894ea2e63aa93d364348081f6bb25049050a1c287004d47ec5454355b84bc66e18a99a53438175768c6c3dff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
