#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAzNKcOjD++zJxMkgK8VNxXwaJqJWQNiN63ndmxpV/2lT2mLD3
    UAm27ju2ZT9SVNf+HLj7LQ2HUmolFkd1B5pbJcNqJ68ABBsx5eYdvYIz426X7THQ
    1CGvis8wht5J4YrOH0dXzl8XyGiKKDO3PemDFJTfgtqFm+YWmo9hOYOopy5qbFtI
    mgEnCxEjQyy8OUs/qoW9t3t88eDR5R6bt3+LFPCX5dMpnXwQpxFO1ZNAakz/2vrt
    sb2J5mF22WkQnDnJn6oUJ73nTAbfNDp2UTCtR6f0l62lvbyoGZ0ZUXHswrflbvOR
    6C8qsRRLVMn3zJ5EfINsLJxUJTx9LqBZG+KqDQIDAQABAoIBAA3CvJJARnEz81zw
    cCPEemJq+wajfbvVaGTX2sTOuHc/rA2YHhV3gZ3Bz0BAH9Tpaf4eA2oEdan4zaMQ
    i/FF0ofX+CLQZAziktiiPC9GNxw5iuV5qlEGLlgCEX2OI6KOg8igL2sDAoMJWvbW
    eqIjNRZF5jpRWhaeP7iEl4CYstUAb1q0zXwa93BH4cslW4arR4Wj6F6LGDIBJh/U
    1mwdkrW+MtgK1Bzp3qJrfhnmuCnhkmO3usivu4fByG0is532nK1Rt598Lto0vErt
    z1SVDpILzVW2MP7T/WXyOXelQJJnaT5GU2WuAHXE8ie4gQ79EUxU2+7Lwpkqgc5x
    6RBu2lUCgYEA/9gapEdR7g/pd6w9UN3xHIWl3uOL8WzpKzqcKwdQgRoTqdmGqvHp
    Io/juyhcCkWdC6ZjgccsJsdI+tCbQaafP08jt5fI36bfpN9r2NuEhNEoiD6N501E
    KZSeto6BUzurJroyxbREWdcdYZsYTh/z0marW4cL4SSS1UV7j7aSVu8CgYEAzPKM
    zAoYxvMrvGQcNTmVMtjbkT1v0mOS4han/DtvPPPGZQ0S3ewN/DPGzzD57QYP0Iwl
    jMzxirAVgjPDeTga4Ygk3En3GnXoWOAcGoAseA20MbYBLZsl3Gw/P5fQjP0jNVWZ
    dFmDFQHic4qtQb7qROK6VslICg9suXjyHYHsrsMCgYAIi6JQLGWrKvLkYWdm5RLh
    ngEtUbJh7P5YyEthEIx603EmsjJSUWQ1GFNF9BIm8a5OLk+SjSGHZg6k+gTFi5g0
    GCOcRUCbX8qGikPi6WoiuY2+B0DcIfON4/3tIRNmwU51K7D4c4345juAABsuuNh/
    BZjhpMAb1Annf7uh0DpRFwKBgGjC4y25S4kG7ChUlAaw9I8VQscvPGWy+HYRVrUc
    PHRPt+4XjLlb3Jo6bTmjs11xZ8wWl2stp5pY/+WaSCVChJscWJsyQ9mGw8oKZNM3
    CYQknSN8AYYqdGQEASCknboz+zdcFiDfUJ4AZJzjGkUtLdsgele6c9SQpeb45+ol
    a7K5AoGBAOgKpjhplBB1FLDxpDSGf5jqS11YmdefCtmgamm5qaDfDbgCTQIX2q98
    65ruSwPfMdW5fPQT58RUsRVvwUdBAGUl+I9lPQPzPZDWzaKaRdpoC5NMwxhtAU/3
    3fGaZpv0ZCD+Vzq+s5hRO349GGZsdDyPFKENGZU/J+gbI4fOFC0J
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key:     "<%= ENV['RELEASE_KEY1'] %>"
      iv:                "BQsXX34UGrMdgi7KE4L9pA=="
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAsSn0duBeVFtlbdST/vegKngjrC3EbAYSIzDAZH0OKUok6k3h
    LW7cZksBGS7YU0b2Uzf3HSya1ABw56haVGysuuhpfFgcVO1GP4twTMZnq8eW4Y/k
    JIZCPMBUhS/Jj8le6mIWZK9c7tCOLJUn2Pfl4Wrpl1IhphRzBhLDhVZRJ+iqR14Z
    7LOjm4aQq3l1oU3IFWB7VDPjQldtBhh62VjAEktD8QCYi4cPo+d9hCf0NvWvnNiL
    EqiCsuL7ZXRIwljcJaJ3Qadqb/YLHPFMuAQENM0BkX67wUQ0PXhawtAAUbHANXX9
    hJ1mGpaL5sN+BX/edDVqwqJqOYHGKztGpdFzZwIDAQABAoIBABel7gfgMzc3a/aZ
    JZgnHa4Nk1VsVofE167y1vuS5c0FJKBR/Pi/j5Pn9yGRazbShhbdpZKzXYdm96s0
    gbo7N2NLmqkKad28PmBFEJxu72+ymKVLO7zUXwsU8TNGCbWzv4OxzCNsdQ87r36r
    +kGv9XN9fejBAdTVbfUllAu8VeDpqKOybf/R3mTHutLxhIsF6pd1wgnkMchhlXzL
    1FobRKkyxeiMWGlordyvIQh5CZgkVROWLx9J5zCbi9xdzrXDLYN44jSAqJbdOnvF
    eLg6yvmRdEqXPqQpzApyIjShDmzTcEdIL5nRlggmYCniJ1Hj0C91cIos+4DKgKs2
    hftHaoECgYEA53m+2gxKtZ+oFJ0HLHgu7XLPSivQFlJ7ceJxVtKAydxy4DaJ/XBq
    QCPPk91qjcoPNhWrNCHgW6Rqjic+cfwrpb89PXAKDmJ13FmC+Gd97pU289DTRCwq
    WFt5m6yzGlifD7So8W2VXGIhLqUKZNxrP8TY18CKRd9cISAmOXuLFrcCgYEAw+8g
    i8eZF3YDQGWkhH3p5dUB/VABmcRVUA1BvLou+E29uiKTm4XVx4AudEGpFssSzZN9
    U4C62k/TA4trAlTP0tNNxAVE82tTbZfFSX7kVlgrepzdS/AoQDEtjKv3HfzDpRGz
    rc1Adof8UeUQgN7GmaxFR8C7noGJN0/vNSUzWNECgYB14Fu+cpABGcLgbG7gyHst
    VFAXd2RKWcqfXi9VhXEsWuTtJRj0RTD2ZMYqiJDgj8tbQYGj1LSKNppEtdto9H/N
    siufg9S7KozWn4bAtQM+YiJP20Ia71rJEBxHmJTEj+jAeMGn4KQ1HYvEUyuN3WmI
    WdgLVvOTTYF/JP4SO8XC1QKBgDi/ODjjrTY7SsPK7HQnF6gmIjZghqYnU+IkhMaJ
    UfM+aNXRD9k6UOk/+bRYFAXy+NYrgl+95+A0wFPFfE+niq1v35UHRaoOipIyI8Se
    iLltPeJ8LifBPZch5yRX5fF8dJmJX/XVfXcW+YAqjLYWT4TQfRxD+NL2h2xKrWhC
    BvYRAoGBAKPD0v4rLz5FulpJ6L7SFmq7L6fvo4ffrNbU78yO3D3Jto5DTR59zagY
    gbBLTfNvZzpwgzYmm9t70CuGlrn+iKlVtD9oSA4kZvaqX6PIJNJ8nKgIWdwV7l5j
    0R+gDBmDWXscbQ4k9Ww1RObOFi778Q2mzG034dm6/kGt231UDNSW
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key:     "<%= ENV['PRODUCTION_KEY1'] %>"
      iv:                "vyOHccyfEr1KFeGvolR7Ow=="
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
